# Generated by Django 4.2.10 on 2024-02-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_story', '0002_story_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
